### ISSUE TITLE
Go get is broken

### ISSUE THREAD

**Issue by hugoboos** [privacybydesign/irmago#105]
Installing this package is broken.

Using Go 1.15.0, on MacOS and Linux.

```
$ go get github.com/privacybydesign/irmago
go: github.com/privacybydesign/irmago upgrade => v0.5.0
go get: github.com/privacybydesign/irmago@v0.5.0 requires
	github.com/spf13/pflag@v1.0.4-0.20190111213756-a45bfec10d59: invalid version: unknown revision a45bfec10d59
```

See also this MR: https://gitlab.com/commonground/nlx/nlx/-/merge_requests/1753, with the failing job: https://gitlab.com/commonground/nlx/nlx/-/jobs/726298670#L23

**Comment by sietseringers** [comment]
Thanks for reporting.

This was because we used `replace` directives in `go.mod` to switch to forks of two packages, which don't automatically apply to importing packages. The `replace` directives are now gone so it should work now.

**Comment by stevenvegt** [comment]
Can you create a new release v0.5.1 which includes these fixes? Otherwise I need to get a master version.
```
go get github.com/privacybydesign/irmago@v0.5.0
go get: github.com/privacybydesign/irmago@v0.5.0 requires
        github.com/spf13/pflag@v1.0.4-0.20190111213756-a45bfec10d59: invalid version: unknown revision a45bfec10d59
```

**Comment by sietseringers** [comment]
Ah yes, apologies. Done.
