### ISSUE TITLE
Log server version at start with loglevel 'info'

### ISSUE THREAD

**Issue by BramWithaar** [privacybydesign/irmago#106]
It would be very convenient if the server could log the server version at start with loglevel info.
It's especially convenient after an upgrade or restart, to check if the correct version is running.

**Comment by sietseringers** [comment]
Indeed, the server does this since version 0.3.0:

<img width="804" alt="Screenshot 2020-09-20 at 14 56 39" src="https://user-images.githubusercontent.com/979897/93711816-888baf80-fb51-11ea-960c-b4c2a5dbb9ee.png">

Does this not work for you?

**Comment by BramWithaar** [comment]
never mind. it works for us as described. I didn't look in the right place.
