### ISSUE TITLE
irma scheme update error type transport 

### ISSUE THREAD

**Issue by CristianPantilie** [privacybydesign/irmago#113]
Hello. I am trying to create my own irma scheme, just to test how it works. I have through all the necessary steps for configuration, uploaded it to a localhost https server (using a self-signed TLS certificate), and whenever I run `irma scheme update`, my new scheme gets an `error type transport`, saying that the GET request for https://localhost:3000/index is giving up after 3 attempts. Testing that endpoint with Postman does give me the appropriate index file. Could it be that I need a trusted TLS certificate or is there something else I am missing?

**Comment by sietseringers** [comment]
Indeed the update command (as well as the rest of `irmago`) only accepts valid certificates (having it accept by default any certificate, valid or not, would be unsafe).

During testing you can instead use plain http, although you will have to set [this boolean](https://github.com/privacybydesign/irmago/blob/master/internal/common/common.go#L25) to false.
