### ISSUE TITLE
Installing irmago from source gives compile error

### ISSUE THREAD

**Issue by davidv1992** [privacybydesign/irmago#121]
Running `go get github.com/privacybydesign/irmago` to install the latest version of irmago from source results in the following compiler output:

```
# github.com/privacybydesign/gabi/signed
go/src/github.com/privacybydesign/gabi/signed/signed.go:126:26: too many arguments in call to cbor.Marshal
	have (interface {}, cbor.EncOptions)
	want (interface {})
go/src/github.com/privacybydesign/gabi/signed/signed.go:135:21: too many arguments in call to cbor.Marshal
	have (*tuple, cbor.EncOptions)
	want (interface {})
```

**Comment by sietseringers** [comment]
Are you running `go get` outside any Go module, by any chance? In that case, `go get` reverts to its pre-module behaviour, i.e. ignore `go.mod` of `irmago` and install the latest versions all of its dependencies in `$GOPATH`. Some time ago the API of `cbor` had a breaking change, but irmago's `go.mod` correctly pins the version that it uses.

If you want to install `irmago` as a dependency of another go project, you should run `go get` inside the directory of that project. If instead you want to install `irma` from source, you should follow the [installation instructions in the documentation](https://irma.app/docs/getting-started/#installing-and-running-irma-server), which uses `git clone` to avoid this.

**Comment by davidv1992** [comment]
Ah, that explains my trouble, thanks for the advice. It might be useful to link to the installation instructions from the irma server documentation and/or the irmago readme, as I hadn't thought to look for that there.
