### ISSUE TITLE
Not able to add cards due to app redirecting to Google Play store (using F-droid version)

### ISSUE THREAD

**Issue by joeyboon** [privacybydesign/irmago#158]
Hi,

As a privacy minded person I use a phone with [Graphene OS ](https://grapheneos.org/) (degoogled and hardend Android). I downloaded the IRMA app from the F-droid store but I'm not able to add cards due to the redirection to the Google Play store. Whenever I try to add a card and click open the app it takes me to the webpage of the IRMA app in Google Play store (which I don't use for obvious reasons ;). If you need me to supply more info let me know!

**Comment by sietseringers** [comment]
Do you use Firefox by any chance? By default, Firefox does not open links to apps, such as IRMA. You can solve this by changing the settings of Firefox. Under "Settings" go to "Advanced" and allow "Open links in apps".

We have a fix for this problem that does not require you to change settings, but that has not yet been deployed everywhere.

**Comment by joeyboon** [comment]
Thanks for the fast reply! I was indeed using Firefox and can confirm this works!
