### ISSUE TITLE
[Unreachable code] func (disjunction *AttributeDisjunction) satisfied()

### ISSUE THREAD

**Issue by mrtuborg** [privacybydesign/irmago#25]
https://github.com/privacybydesign/irmago/blob/d08590e22f04927fb6a7a4696e76a8de8190ff5a/attributes.go#L387

In which condition this `return false` should be executed?
Or it is just copy&paste issue here?

**Comment by sietseringers** [comment]
That shouldn't be there, I'll remove it. I think it was indeed a copy-paste error. Thanks!
