### ISSUE TITLE
Shouldn't `irma genkeypair` be part of `irma scheme`?

### ISSUE THREAD

**Issue by confiks** [privacybydesign/irmago#29]
There's also a potential confusion between the two types of keypairs.

**Comment by sietseringers** [comment]
`irma scheme` currently only operates on schemes as a whole, so issuer key generation doesn't really fit in.

How about a new `issuer` subcommand, i.e.
```
irma issuer keygen
```
also resolving the `genkeypair`/`keygen` name inconsistenty in favor of the latter. `irma issuer` can later get more subcommands (e.g. generate a new issuer skeleton).

**Comment by confiks** [comment]
I don't entirely agree that generating an issuer keypair doesn't fit in with the scheme command, as issuers are part of the scheme, but your proposed solution sounds good.

`irma scheme issuer keygen` might be another option, but that introduces yet another level of nesting. Hypothetically, `irma scheme issuer new` could also exist, to enter a wizard to create a new issuer (or create a template file).
