### ISSUE TITLE
Configuring IRMA Server to work on HTTPS

### ISSUE THREAD

**Issue by shashankjayajain** [privacybydesign/irmago#41]
Hello IRMA Team,

I am trying to configure IRMA server to work on HTTPS,

Executed following command to run the server:

irma server -v --tls-cert-file xxx.crt --tls-privkey-file xxx.key &> irma-logs.txt & 

The IRMA runs fine. It generates new session properly. But when I try to scan it using IRMA Mobile app. It does not work, shows following log in the file

TLS handshake error from XX.XX.XX.XX:PORT: remote error: tls: bad certificate

**Comment by sietseringers** [comment]
So to summarize, you can talk to the server (as you can `POST` your session request), but the IRMA app cannot?

Perhaps the app aborts the connection because the full certificate chain is not installed? You can include the entire chain in the certificate file, like you would for e.g. nginx.

**Comment by shashankjayajain** [comment]
Yes I can post a session request successfully from my web application.
In the web app I use "https://www.domain.name:port" so it works.
but when I scan the generated QR code using IRMA app it results in "https://IP-address:port". can this be an issue?

**Comment by sietseringers** [comment]
I guess that is the problem, yes (although I would expect a different error message than `bad certificate`). You can configure what the server puts in the QR with the `--url` flag, i.e. `--url https://www.domain.name:port`.

**Comment by shashankjayajain** [comment]
I see following logs after adding the above changes

2019/05/07 08:25:56 http: TLS handshake error from 182.74.185.238:49697: remote error: tls: bad certificate
time="2019-05-07T08:25:56Z" level=debug msg="Routing protocol message" method=GET path="irma/sPMdIySKJtjUeD9dZXhd/status"
2019/05/07 08:25:56 http: TLS handshake error from 182.74.185.238:49698: remote error: tls: bad certificate
time="2019-05-07T08:25:57Z" level=debug msg="Routing protocol message" method=GET path="irma/sPMdIySKJtjUeD9dZXhd/status"
2019/05/07 08:25:57 http: TLS handshake error from 182.74.185.238:49699: remote error: tls: bad certificate
time="2019-05-07T08:25:57Z" level=debug msg="Routing protocol message" method=GET path="irma/sPMdIySKJtjUeD9dZXhd/status"
2019/05/07 08:25:58 http: TLS handshake error from 182.74.185.238:49700: remote error: tls: bad certificate
2019/05/07 08:25:58 http: TLS handshake error from 182.74.185.238:49701: remote error: tls: bad certificate
time="2019-05-07T08:25:58Z" level=debug msg="Routing protocol message" method=GET path="irma/sPMdIySKJtjUeD9dZXhd/status"
2019/05/07 08:25:58 http: TLS handshake error from 182.74.185.238:49702: remote error: tls: bad certificate
time="2019-05-07T08:25:59Z" level=debug msg="Routing protocol message" method=GET path="irma/sPMdIySKJtjUeD9dZXhd/status"
2019/05/07 08:25:59 http: TLS handshake error from 182.74.185.238:49703: remote error: tls: bad certificate
time="2019-05-07T08:25:59Z" level=debug msg="Routing protocol message" method=GET path="irma/sPMdIySKJtjUeD9dZXhd/status"
2019/05/07 08:26:00 http: TLS handshake error from 182.74.185.238:49704: remote error: tls: bad certificate
time="2019-05-07T08:26:00Z" level=debug msg="Routing protocol message" method=GET path="irma/sPMdIySKJtjUeD9dZXhd/status"

**Comment by shashankjayajain** [comment]
Command I used

irma server -v --tls-cert-file xxx.crt --tls-privkey-file xxx.key --url https://www.domain.name:port &> irma-logs.txt &

**Comment by davidv1992** [comment]
A few questions to help us debug this:

Which device is running on the IP address 182.74....? (Is that the phone, or a desktop?)
How are you starting sessions?
Is xxx.crt the full chain of certificates, or only the final one?

**Comment by shashankjayajain** [comment]
Which device is running on the IP address 182.74....? (Is that the phone, or a desktop?)
Ans: phone

How are you starting sessions?
Ans: Web application with irmajs library integrated starts the session on user interaction. It is configured to call IRMA server hosted at https://www.domain.name:port

Is xxx.crt the full chain of certificates, or only the final one?
Final one

**Comment by shashankjayajain** [comment]
Which device is running on the IP address 182.74....? (Is that the phone, or a desktop?)
phone

How are you starting sessions?
Web application with irmajs library integrated starts the session on user interaction. It is configured to call IRMA server hosted at https://www.domain.name:port

Is xxx.crt the full chain of certificates, or only the final one?
Not sure

**Comment by davidv1992** [comment]
For the certificate, it is recommended to use the full chain.

2nd: is the root certificate for the ssl certificate you use trusted by the telephone?

**Comment by shashankjayajain** [comment]
is the root certificate for the ssl certificate you use trusted by the telephone?
yes

Will make sure full chain is configured and revert if that doesn't work. Thank you

**Comment by shashankjayajain** [comment]
Thank you very much IRMA team.
It works when full chain certs file is passed to --tls-cert-file flag

irma server -v --tls-cert-file xxx.chained.crt --tls-privkey-file xxx.key --url https://domain.name:port &> xxx.txt &

very much appreciate your support @davidv1992 & @sietseringers .

**Comment by sietseringers** [comment]
You're welcome!
