### ISSUE TITLE
Add test status and code coverage integrations

### ISSUE THREAD

**Issue by stevenvegt** [privacybydesign/irmago#45]
Since running the test locally requires some setup with a local key servers etc. I like to see if a branch or commit passes all the tests. Also it would be nice to see what is tested and what is not. 

Can you add some integrations for build status from travis-ci or some other automated tool combined with something like codecov?

**Comment by sietseringers** [comment]
We're working on a CI server that will automatically test all commits.

In the meantime you can run almost all of the tests included in `irmago` yourself, by excluding the ones that require a keyshare server, using the `local_tests` build tag as follows:
```
go test -p 1 --tags=local_tests ./...
```
This currently excludes 5 of the tests, and requires no other servers to be running.

(The section on testing in README.md is woefully out of date; I will update it soon.)
