### ISSUE TITLE
Sharing BSN Information shows error message

### ISSUE THREAD

**Issue by shashankjayajain** [privacybydesign/irmago#52]
Hello IRMA Team,

I am facing an issue when sharing BSN attribute from IRMA android app to another android app. Following error message is shown while sharing the attribute.

![Screenshot_20190528-123845_Chrome](https://user-images.githubusercontent.com/48466924/59007984-84e1f580-8846-11e9-9c13-f6bfd872695e.jpg)

**Comment by davidv1992** [comment]
Unfortunately, this error message comes from the app you are trying to use, and not irma itself. You should contact the support for that app for help with this particular issue.

**Comment by confiks** [comment]
@shashankjayajain Could you be more specific in what you're trying to do when that error comes along?

I'm also quite interested in what kind of project you're working on.
