### ISSUE TITLE
Setting `disable_schemes_update` does not have effect

### ISSUE THREAD

**Issue by hugoboos** [privacybydesign/irmago#63]
When using the `irma server`, setting the `disable_schemes_update` config option to `true` does not have effect.

```yaml
disable_schemes_update: true
```

To disable it you need to set the interval to `0`, but the `schemes_update` won't change.

```yaml
schemes_update: 0
```

```
time="2019-10-10T10:26:19Z" level=debug msg="Configuration: {
   "schemes_path": "/usr/local/share/irma/irma_configuration",
   "schemes_assets_path": "",
   "disable_schemes_update": true,
   "schemes_update": 60,
   ...
```

Also the documentation is contradicting:
https://github.com/privacybydesign/irmago/blob/master/server/api.go#L39

Found the problem on line: https://github.com/privacybydesign/irmago/blob/master/server/irmad/cmd/root.go#L216

**Comment by sietseringers** [comment]
The handling of these variables is indeed a little confusing, I'll see if that can be made more clear.

The current way for instructing the `irma server` not to update schemes is to set the `schemes_update` option to `0`. That will work (if you pass `-v` or `-vv`, you'll see no HTTP calls to the IRMA schemes), even though the printed configuration claims it is set to 60.

The `disable_schemes_update` flag was only meant to be used when using the `irmaserver` library. The reason for this is that when you use Go (as opposed to the `irma server` on the command line) the distinction between `schemes_update` being set to 0 or being absent from the `Configuration` struct is impossible to detect, so I had to introduce this boolean to allow users to disable scheme updating in this case. Consequentially, the `irma server` does not know of the `disable_schemes_update` flag and so ignores it when you put it in a configuration file.

**Comment by sietseringers** [comment]
Fixed (in `master`) as follows:
* The `disable_schemes_update` option now works as expected;
* If specified then the printed configuration will show `schemes_update` to equal `0`;
* As before, if `schemes_update` is set to `0` then scheme updating is also disabled.
