### ISSUE TITLE
go mod?

### ISSUE THREAD

**Issue by johanhenselmans** [privacybydesign/irmago#78]
Shouldn't it be wise to migrate to go.mod in the code and the documentation?

I did a go mod init irmago in the irmago folder and it seems that everything works.

**Comment by johanhenselmans** [comment]
OK, after go mod init irmago I had to change one thing:

replace github.com/spf13/pflag v1.0.5 => github.com/sietseringers/pflag v1.0.4-0.20190111213756-a45bfec10d59

replace github.com/spf13/viper v1.5.0 => github.com/sietseringers/viper v1.0.1-0.20190113114857-554683669b21
and remove github.com/sietseringers/ from the 
require ()
section. 


[go.mod.zip](https://github.com/privacybydesign/irmago/files/3906306/go.mod.zip)

doing ggo test -v -p 1 --tags=local_tests ./... however, gives the following errors:

transport.go:21:2: use of internal package github.com/privacybydesign/irmago/internal/disable_sigpipe not allowed
descriptions.go:9:2: use of internal package github.com/privacybydesign/irmago/internal/fs not allowed
internal/servercore/api.go:21:2: use of internal package github.com/privacybydesign/irmago/internal/fs not allowed
internal/test/testdata.go:15:2: use of internal package github.com/privacybydesign/irmago/internal/fs not allowed
irma/cmd/download.go:11:2: use of internal package github.com/privacybydesign/irmago/internal/fs not allowed
irmaclient/client.go:14:2: use of internal package github.com/privacybydesign/irmago/internal/fs not allowed
server/api.go:20:2: use of internal package github.com/privacybydesign/irmago/internal/fs not allowed
server/irmac/capi.go:28:2: use of internal package github.com/privacybydesign/irmago/internal/servercore not allowed
server/irmaserver/main.go:13:2: use of internal package github.com/privacybydesign/irmago/internal/servercore not allowed
server/requestorserver/auth.go:11:2: use of internal package github.com/privacybydesign/irmago/internal/fs not allowed

**Comment by sietseringers** [comment]
We now use Go modules.
